"""Начальные категории и события (демо-данные для пустой БД)."""

CATEGORY_SEEDS: list[dict[str, int | str]] = [
    {"id": 1, "name": "Концерты"},
    {"id": 2, "name": "Театр"},
    {"id": 3, "name": "Выставки"},
    {"id": 4, "name": "Кино"},
    {"id": 5, "name": "Лекции"},
    {"id": 6, "name": "Настолки"},
    {"id": 7, "name": "Видеоигры"},
    {"id": 8, "name": "Квизы"},
    {"id": 9, "name": "Мастер-классы"},
    {"id": 10, "name": "Рукоделие"},
    {"id": 11, "name": "Командный спорт"},
    {"id": 12, "name": "Фитнес/йога"},
    {"id": 13, "name": "Бег/вело"},
    {"id": 14, "name": "Единоборства"},
    {"id": 15, "name": "Экстрим"},
    {"id": 16, "name": "Фуд-фестивали"},
    {"id": 17, "name": "Дегустации"},
    {"id": 18, "name": "Ярмарки"},
    {"id": 19, "name": "Акции магазинов"},
    {"id": 20, "name": "Свопы"},
    {"id": 21, "name": "Нетворкинг"},
    {"id": 22, "name": "Языковые клубы"},
    {"id": 23, "name": "Клубы по интересам"},
    {"id": 24, "name": "Знакомства"},
    {"id": 25, "name": "Городские праздники"},
    {"id": 26, "name": "Музыкальные фестивали"},
    {"id": 27, "name": "Уличная культура"},
    {"id": 28, "name": "Детские фестивали"},
    {"id": 29, "name": "Медитация"},
    {"id": 30, "name": "Психологические группы"},
    {"id": 31, "name": "Благотворительные забеги"},
]

EVENT_SEEDS: list[dict[str, object]] = [
    {
        "id": 101,
        "title": "Лекция по искусственному интеллекту",
        "event_datetime": "2026-05-20T18:00:00+03:00",
        "location": "ул. Пушкина, 10",
        "price": 500,
        "average_rating": 4.8,
        "cover_image_url": None,
        "latitude": 55.763,
        "longitude": 37.609,
        "category_id": 5,
        "is_for_children": False,
        "age_rating_min": 12,
    },
    {
        "id": 102,
        "title": "Настольные игры в антикафе",
        "event_datetime": "2026-05-25T18:30:00+03:00",
        "location": "Антикафе «Игротека»",
        "price": 0,
        "average_rating": 4.7,
        "cover_image_url": None,
        "latitude": 55.740,
        "longitude": 37.580,
        "category_id": 6,
        "is_for_children": True,
        "age_rating_min": 6,
    },
    {
        "id": 103,
        "title": "Футбол: дерби сезона",
        "event_datetime": "2026-06-01T19:00:00+03:00",
        "location": "ВЭБ Арена",
        "price": 1200,
        "average_rating": 4.6,
        "cover_image_url": None,
        "latitude": 55.800,
        "longitude": 37.514,
        "category_id": 11,
        "is_for_children": False,
        "age_rating_min": 0,
    },
    {
        "id": 104,
        "title": "Джазовый вечер на крыше",
        "event_datetime": "2026-05-18T20:00:00+03:00",
        "location": "Крыша «Высота 57»",
        "price": 1500,
        "average_rating": 4.9,
        "cover_image_url": None,
        "latitude": 55.758,
        "longitude": 37.621,
        "category_id": 1,
        "is_for_children": False,
        "age_rating_min": 18,
    },
    {
        "id": 105,
        "title": "Иммерсивный спектакль «Ночной город»",
        "event_datetime": "2026-05-22T19:30:00+03:00",
        "location": "Театр «Новая сцена»",
        "price": 2300,
        "average_rating": 4.7,
        "cover_image_url": None,
        "latitude": 55.745,
        "longitude": 37.602,
        "category_id": 2,
        "is_for_children": False,
        "age_rating_min": 16,
    },
    {
        "id": 106,
        "title": "Фестиваль уличной еды",
        "event_datetime": "2026-05-30T13:00:00+03:00",
        "location": "Хлебозавод",
        "price": 0,
        "average_rating": 4.5,
        "cover_image_url": None,
        "latitude": 55.804,
        "longitude": 37.585,
        "category_id": 16,
        "is_for_children": True,
        "age_rating_min": 0,
    },
    {
        "id": 107,
        "title": "Выставка digital-арта",
        "event_datetime": "2026-05-27T12:00:00+03:00",
        "location": "ЦСИ «Фабрика»",
        "price": 700,
        "average_rating": 4.4,
        "cover_image_url": None,
        "latitude": 55.767,
        "longitude": 37.667,
        "category_id": 3,
        "is_for_children": False,
        "age_rating_min": 12,
    },
    {
        "id": 108,
        "title": "Киноночь: фантастика 80-х",
        "event_datetime": "2026-05-24T22:00:00+03:00",
        "location": "Киноцентр «Октябрь»",
        "price": 900,
        "average_rating": 4.6,
        "cover_image_url": None,
        "latitude": 55.752,
        "longitude": 37.583,
        "category_id": 4,
        "is_for_children": True,
        "age_rating_min": 12,
    },
    {
        "id": 109,
        "title": "Йога в парке Горького",
        "event_datetime": "2026-05-19T08:00:00+03:00",
        "location": "Парк Горького",
        "price": 0,
        "average_rating": 4.3,
        "cover_image_url": None,
        "latitude": 55.730,
        "longitude": 37.601,
        "category_id": 12,
        "is_for_children": True,
        "age_rating_min": 0,
    },
    {
        "id": 110,
        "title": "Открытый микрофон стендапа",
        "event_datetime": "2026-05-28T20:30:00+03:00",
        "location": "Клуб «Сцена»",
        "price": 400,
        "average_rating": 4.2,
        "cover_image_url": None,
        "latitude": 55.773,
        "longitude": 37.649,
        "category_id": 1,
        "is_for_children": False,
        "age_rating_min": 18,
    },
    {
        "id": 111,
        "title": "Квиз по сериалам",
        "event_datetime": "2026-05-21T19:00:00+03:00",
        "location": "Бар «Штаб»",
        "price": 600,
        "average_rating": 4.8,
        "cover_image_url": None,
        "latitude": 55.782,
        "longitude": 37.599,
        "category_id": 8,
        "is_for_children": False,
        "age_rating_min": 16,
    },
    {
        "id": 112,
        "title": "Балет «Лебединое озеро»",
        "event_datetime": "2026-06-03T19:00:00+03:00",
        "location": "Большой театр",
        "price": 3500,
        "average_rating": 5.0,
        "cover_image_url": None,
        "latitude": 55.760,
        "longitude": 37.618,
        "category_id": 2,
        "is_for_children": False,
        "age_rating_min": 6,
    },
    {
        "id": 113,
        "title": "Маркет локальных брендов",
        "event_datetime": "2026-05-31T12:00:00+03:00",
        "location": "Депо. Три вокзала",
        "price": 0,
        "average_rating": 4.1,
        "cover_image_url": None,
        "latitude": 55.779,
        "longitude": 37.656,
        "category_id": 18,
        "is_for_children": False,
        "age_rating_min": 0,
    },
    {
        "id": 114,
        "title": "Воркшоп по UX-дизайну",
        "event_datetime": "2026-06-05T18:30:00+03:00",
        "location": "Технопарк «Сколково»",
        "price": 1800,
        "average_rating": 4.7,
        "cover_image_url": None,
        "latitude": 55.698,
        "longitude": 37.349,
        "category_id": 9,
        "is_for_children": False,
        "age_rating_min": 16,
    },
]
