"""Начальные категории и события (демо-данные для пустой БД)."""

CATEGORY_SEEDS: list[dict[str, int | str]] = [
    {"id": 1, "name": "Концерты"},
    {"id": 2, "name": "Театр"},
    {"id": 3, "name": "Выставки"},
    {"id": 4, "name": "Кино"},
    {"id": 5, "name": "Лекции"},
    {"id": 6, "name": "Настолки"},
    {"id": 7, "name": "Видеоигры"},
    {"id": 8, "name": "Квизы"},
    {"id": 9, "name": "Мастер-классы"},
    {"id": 10, "name": "Рукоделие"},
    {"id": 11, "name": "Командный спорт"},
    {"id": 12, "name": "Фитнес/йога"},
    {"id": 13, "name": "Бег/вело"},
    {"id": 14, "name": "Единоборства"},
    {"id": 15, "name": "Экстрим"},
    {"id": 16, "name": "Фуд-фестивали"},
    {"id": 17, "name": "Дегустации"},
    {"id": 18, "name": "Ярмарки"},
    {"id": 19, "name": "Акции магазинов"},
    {"id": 20, "name": "Свопы"},
    {"id": 21, "name": "Нетворкинг"},
    {"id": 22, "name": "Языковые клубы"},
    {"id": 23, "name": "Клубы по интересам"},
    {"id": 24, "name": "Знакомства"},
    {"id": 25, "name": "Городские праздники"},
    {"id": 26, "name": "Музыкальные фестивали"},
    {"id": 27, "name": "Уличная культура"},
    {"id": 28, "name": "Детские фестивали"},
    {"id": 29, "name": "Медитация"},
    {"id": 30, "name": "Психологические группы"},
    {"id": 31, "name": "Благотворительные забеги"},
]

EVENT_SEEDS: list[dict[str, object]] = [
    {
        "id": 101,
        "title": "Лекция по искусственному интеллекту",
        "event_datetime": "2026-06-08T18:00:00+03:00",
        "location": "ул. Пушкина, 10",
        "price": 500,
        "average_rating": 4.8,
        "cover_image_url": None,
        "latitude": 55.763,
        "longitude": 37.609,
        "category_id": 5,
        "is_for_children": False,
        "age_rating_min": 12,
    },
    {
        "id": 102,
        "title": "Настольные игры в антикафе",
        "event_datetime": "2026-06-05T18:30:00+03:00",
        "location": "Антикафе «Игротека»",
        "price": 0,
        "average_rating": 4.7,
        "cover_image_url": None,
        "latitude": 55.740,
        "longitude": 37.580,
        "category_id": 6,
        "is_for_children": True,
        "age_rating_min": 6,
    },
    {
        "id": 103,
        "title": "Футбол: дерби сезона",
        "event_datetime": "2026-06-06T19:00:00+03:00",
        "location": "ВЭБ Арена",
        "price": 1200,
        "average_rating": 4.6,
        "cover_image_url": None,
        "latitude": 55.800,
        "longitude": 37.514,
        "category_id": 11,
        "is_for_children": False,
        "age_rating_min": 0,
    },
    {
        "id": 104,
        "title": "Джазовый вечер на крыше",
        "event_datetime": "2026-06-14T20:00:00+03:00",
        "location": "Крыша «Высота 57»",
        "price": 1500,
        "average_rating": 4.9,
        "cover_image_url": None,
        "latitude": 55.758,
        "longitude": 37.621,
        "category_id": 1,
        "is_for_children": False,
        "age_rating_min": 18,
    },
    {
        "id": 105,
        "title": "Иммерсивный спектакль «Ночной город»",
        "event_datetime": "2026-06-04T19:30:00+03:00",
        "location": "Театр «Новая сцена»",
        "price": 2300,
        "average_rating": 4.7,
        "cover_image_url": None,
        "latitude": 55.745,
        "longitude": 37.602,
        "category_id": 2,
        "is_for_children": False,
        "age_rating_min": 16,
    },
    {
        "id": 106,
        "title": "Фестиваль уличной еды",
        "event_datetime": "2026-06-07T13:00:00+03:00",
        "location": "Хлебозавод",
        "price": 0,
        "average_rating": 4.5,
        "cover_image_url": None,
        "latitude": 55.804,
        "longitude": 37.585,
        "category_id": 16,
        "is_for_children": True,
        "age_rating_min": 0,
    },
    {
        "id": 107,
        "title": "Выставка digital-арта",
        "event_datetime": "2026-06-11T12:00:00+03:00",
        "location": "ЦСИ «Фабрика»",
        "price": 700,
        "average_rating": 4.4,
        "cover_image_url": None,
        "latitude": 55.767,
        "longitude": 37.667,
        "category_id": 3,
        "is_for_children": False,
        "age_rating_min": 12,
    },
    {
        "id": 108,
        "title": "Киноночь: фантастика 80-х",
        "event_datetime": "2026-06-13T22:00:00+03:00",
        "location": "Киноцентр «Октябрь»",
        "price": 900,
        "average_rating": 4.6,
        "cover_image_url": None,
        "latitude": 55.752,
        "longitude": 37.583,
        "category_id": 4,
        "is_for_children": True,
        "age_rating_min": 12,
    },
    {
        "id": 109,
        "title": "Йога в парке Горького",
        "event_datetime": "2026-06-10T08:00:00+03:00",
        "location": "Парк Горького",
        "price": 0,
        "average_rating": 4.3,
        "cover_image_url": None,
        "latitude": 55.730,
        "longitude": 37.601,
        "category_id": 12,
        "is_for_children": True,
        "age_rating_min": 0,
    },
    {
        "id": 110,
        "title": "Открытый микрофон стендапа",
        "event_datetime": "2026-06-15T20:30:00+03:00",
        "location": "Клуб «Сцена»",
        "price": 400,
        "average_rating": 4.2,
        "cover_image_url": None,
        "latitude": 55.773,
        "longitude": 37.649,
        "category_id": 1,
        "is_for_children": False,
        "age_rating_min": 18,
    },
    {
        "id": 111,
        "title": "Квиз по сериалам",
        "event_datetime": "2026-06-03T19:00:00+03:00",
        "location": "Бар «Штаб»",
        "price": 600,
        "average_rating": 4.8,
        "cover_image_url": None,
        "latitude": 55.782,
        "longitude": 37.599,
        "category_id": 8,
        "is_for_children": False,
        "age_rating_min": 16,
    },
    {
        "id": 112,
        "title": "Балет «Лебединое озеро»",
        "event_datetime": "2026-06-21T19:00:00+03:00",
        "location": "Большой театр",
        "price": 3500,
        "average_rating": 5.0,
        "cover_image_url": None,
        "latitude": 55.760,
        "longitude": 37.618,
        "category_id": 2,
        "is_for_children": False,
        "age_rating_min": 6,
    },
    {
        "id": 113,
        "title": "Маркет локальных брендов",
        "event_datetime": "2026-06-08T12:00:00+03:00",
        "location": "Депо. Три вокзала",
        "price": 0,
        "average_rating": 4.1,
        "cover_image_url": None,
        "latitude": 55.779,
        "longitude": 37.656,
        "category_id": 18,
        "is_for_children": False,
        "age_rating_min": 0,
    },
    {
        "id": 114,
        "title": "Воркшоп по UX-дизайну",
        "event_datetime": "2026-06-12T18:30:00+03:00",
        "location": "Технопарк «Сколково»",
        "price": 1800,
        "average_rating": 4.7,
        "cover_image_url": None,
        "latitude": 55.698,
        "longitude": 37.349,
        "category_id": 9,
        "is_for_children": False,
        "age_rating_min": 16,
    },
    {
        "id": 115,
        "title": "Ночной маркет дизайнеров",
        "event_datetime": "2026-06-16T17:00:00+03:00",
        "location": "Artplay",
        "price": 300,
        "average_rating": 4.6,
        "cover_image_url": None,
        "latitude": 55.752,
        "longitude": 37.669,
        "category_id": 18,
        "is_for_children": False,
        "age_rating_min": 12,
    },
    {
        "id": 116,
        "title": "Кинопоказ под открытым небом",
        "event_datetime": "2026-06-20T21:30:00+03:00",
        "location": "Парк «Красная Пресня»",
        "price": 800,
        "average_rating": 4.5,
        "cover_image_url": None,
        "latitude": 55.760,
        "longitude": 37.555,
        "category_id": 4,
        "is_for_children": True,
        "age_rating_min": 12,
    },
    {
        "id": 117,
        "title": "Митап: бэкенд на Python и Go",
        "event_datetime": "2026-06-18T19:00:00+03:00",
        "location": "Коворкинг «Точка кипения»",
        "price": 0,
        "average_rating": 4.7,
        "cover_image_url": None,
        "latitude": 55.748,
        "longitude": 37.534,
        "category_id": 21,
        "is_for_children": False,
        "age_rating_min": 16,
    },
    {
        "id": 118,
        "title": "Сити-квест «Секреты Арбата»",
        "event_datetime": "2026-06-22T11:00:00+03:00",
        "location": "Старт: метро Арбатская",
        "price": 1200,
        "average_rating": 4.4,
        "cover_image_url": None,
        "latitude": 55.752,
        "longitude": 37.601,
        "category_id": 15,
        "is_for_children": True,
        "age_rating_min": 6,
    },
    {
        "id": 119,
        "title": "Фестиваль крафтового кофе",
        "event_datetime": "2026-06-19T10:00:00+03:00",
        "location": "Лофт «Зарядье»",
        "price": 400,
        "average_rating": 4.8,
        "cover_image_url": None,
        "latitude": 55.751,
        "longitude": 37.628,
        "category_id": 17,
        "is_for_children": False,
        "age_rating_min": 0,
    },
    {
        "id": 120,
        "title": "Симфонический концерт на закате",
        "event_datetime": "2026-06-28T20:00:00+03:00",
        "location": "Площадка у Москва-реки",
        "price": 2500,
        "average_rating": 4.9,
        "cover_image_url": None,
        "latitude": 55.748,
        "longitude": 37.542,
        "category_id": 1,
        "is_for_children": False,
        "age_rating_min": 6,
    },
    {
        "id": 121,
        "title": "Турнир по Counter-Strike 2",
        "event_datetime": "2026-06-23T16:00:00+03:00",
        "location": "Киберспортивная арена «Colizeum»",
        "price": 800,
        "average_rating": 4.5,
        "cover_image_url": None,
        "latitude": 55.771,
        "longitude": 37.635,
        "category_id": 7,
        "is_for_children": False,
        "age_rating_min": 16,
    },
    {
        "id": 122,
        "title": "Мастер-класс: керамика для начинающих",
        "event_datetime": "2026-06-25T14:00:00+03:00",
        "location": "Студия «Глина и огонь»",
        "price": 2200,
        "average_rating": 4.6,
        "cover_image_url": None,
        "latitude": 55.736,
        "longitude": 37.593,
        "category_id": 10,
        "is_for_children": False,
        "age_rating_min": 14,
    },
    {
        "id": 123,
        "title": "Велозаезд по набережной",
        "event_datetime": "2026-06-26T09:00:00+03:00",
        "location": "Старт: Крымский мост",
        "price": 0,
        "average_rating": 4.4,
        "cover_image_url": None,
        "latitude": 55.731,
        "longitude": 37.601,
        "category_id": 13,
        "is_for_children": True,
        "age_rating_min": 12,
    },
    {
        "id": 124,
        "title": "Тренировка по боксу для новичков",
        "event_datetime": "2026-06-27T18:00:00+03:00",
        "location": "Зал «Fight Club»",
        "price": 900,
        "average_rating": 4.3,
        "cover_image_url": None,
        "latitude": 55.789,
        "longitude": 37.558,
        "category_id": 14,
        "is_for_children": False,
        "age_rating_min": 18,
    },
    {
        "id": 125,
        "title": "Английский разговорный клуб",
        "event_datetime": "2026-06-24T19:30:00+03:00",
        "location": "Кафе «Speak Easy»",
        "price": 350,
        "average_rating": 4.7,
        "cover_image_url": None,
        "latitude": 55.757,
        "longitude": 37.645,
        "category_id": 22,
        "is_for_children": False,
        "age_rating_min": 16,
    },
    {
        "id": 126,
        "title": "Фестиваль «Пикник на Вас»",
        "event_datetime": "2026-06-29T12:00:00+03:00",
        "location": "Музеон",
        "price": 3500,
        "average_rating": 4.9,
        "cover_image_url": None,
        "latitude": 55.734,
        "longitude": 37.606,
        "category_id": 26,
        "is_for_children": False,
        "age_rating_min": 16,
    },
    {
        "id": 127,
        "title": "Медитация на рассвете",
        "event_datetime": "2026-06-30T06:30:00+03:00",
        "location": "Парк «Сокольники»",
        "price": 0,
        "average_rating": 4.5,
        "cover_image_url": None,
        "latitude": 55.794,
        "longitude": 37.675,
        "category_id": 29,
        "is_for_children": True,
        "age_rating_min": 12,
    },
    {
        "id": 128,
        "title": "Благотворительный забег 5 км",
        "event_datetime": "2026-07-05T09:00:00+03:00",
        "location": "Лужники, стартовая зона",
        "price": 500,
        "average_rating": 4.8,
        "cover_image_url": None,
        "latitude": 55.715,
        "longitude": 37.554,
        "category_id": 31,
        "is_for_children": True,
        "age_rating_min": 0,
    },
    {
        "id": 129,
        "title": "Детский праздник «Солнечный город»",
        "event_datetime": "2026-07-06T11:00:00+03:00",
        "location": "Парк «Сад будущего»",
        "price": 0,
        "average_rating": 4.6,
        "cover_image_url": None,
        "latitude": 55.692,
        "longitude": 37.534,
        "category_id": 28,
        "is_for_children": True,
        "age_rating_min": 0,
    },
    {
        "id": 130,
        "title": "Speed dating: вечер знакомств",
        "event_datetime": "2026-07-12T20:00:00+03:00",
        "location": "Лофт «Встреча»",
        "price": 1200,
        "average_rating": 4.2,
        "cover_image_url": None,
        "latitude": 55.764,
        "longitude": 37.622,
        "category_id": 24,
        "is_for_children": False,
        "age_rating_min": 21,
    },
    {
        "id": 131,
        "title": "Балет «Щелкунчик»",
        "event_datetime": "2026-06-10T19:00:00+03:00",
        "location": "Мариинский театр",
        "city": "Санкт-Петербург",
        "price": 4200,
        "average_rating": 4.9,
        "cover_image_url": None,
        "latitude": 59.9253,
        "longitude": 30.2953,
        "category_id": 2,
        "is_for_children": True,
        "age_rating_min": 6,
    },
    {
        "id": 132,
        "title": "Прогулка по белым ночам",
        "event_datetime": "2026-06-14T22:00:00+03:00",
        "location": "Дворцовая набережная",
        "city": "Санкт-Петербург",
        "price": 0,
        "average_rating": 4.8,
        "cover_image_url": None,
        "latitude": 59.9400,
        "longitude": 30.3128,
        "category_id": 27,
        "is_for_children": True,
        "age_rating_min": 0,
    },
    {
        "id": 133,
        "title": "Квиз «Питер глазами местных»",
        "event_datetime": "2026-06-17T20:00:00+03:00",
        "location": "Бар «Биржа»",
        "city": "Санкт-Петербург",
        "price": 700,
        "average_rating": 4.6,
        "cover_image_url": None,
        "latitude": 59.9357,
        "longitude": 30.3259,
        "category_id": 8,
        "is_for_children": False,
        "age_rating_min": 18,
    },
    {
        "id": 134,
        "title": "Фуд-маркет на Севкабеле",
        "event_datetime": "2026-06-20T12:00:00+03:00",
        "location": "Севкабель Порт",
        "city": "Санкт-Петербург",
        "price": 0,
        "average_rating": 4.7,
        "cover_image_url": None,
        "latitude": 59.9225,
        "longitude": 30.2365,
        "category_id": 16,
        "is_for_children": True,
        "age_rating_min": 0,
    },
    {
        "id": 135,
        "title": "Выставка «Импрессионисты в Эрмитаже»",
        "event_datetime": "2026-06-24T11:00:00+03:00",
        "location": "Главный штаб Эрмитажа",
        "city": "Санкт-Петербург",
        "price": 900,
        "average_rating": 4.8,
        "cover_image_url": None,
        "latitude": 59.9398,
        "longitude": 30.3146,
        "category_id": 3,
        "is_for_children": False,
        "age_rating_min": 12,
    },
    {
        "id": 136,
        "title": "Йога в Летнем саду",
        "event_datetime": "2026-06-28T08:00:00+03:00",
        "location": "Летний сад",
        "city": "Санкт-Петербург",
        "price": 0,
        "average_rating": 4.5,
        "cover_image_url": None,
        "latitude": 59.9444,
        "longitude": 30.3350,
        "category_id": 12,
        "is_for_children": True,
        "age_rating_min": 12,
    },
    {
        "id": 137,
        "title": "Лекция об архитектуре модерна",
        "event_datetime": "2026-06-11T18:30:00+05:00",
        "location": "Ельцин Центр",
        "city": "Екатеринбург",
        "price": 600,
        "average_rating": 4.7,
        "cover_image_url": None,
        "latitude": 56.8431,
        "longitude": 60.6100,
        "category_id": 5,
        "is_for_children": False,
        "age_rating_min": 14,
    },
    {
        "id": 138,
        "title": "Симфонический концерт",
        "event_datetime": "2026-06-15T19:00:00+05:00",
        "location": "Дворец молодёжи",
        "city": "Екатеринбург",
        "price": 1800,
        "average_rating": 4.8,
        "cover_image_url": None,
        "latitude": 56.8359,
        "longitude": 60.6094,
        "category_id": 1,
        "is_for_children": False,
        "age_rating_min": 6,
    },
    {
        "id": 139,
        "title": "Настольные игры в антикафе",
        "event_datetime": "2026-06-18T19:00:00+05:00",
        "location": "Антикафе «Кубик»",
        "city": "Екатеринбург",
        "price": 0,
        "average_rating": 4.6,
        "cover_image_url": None,
        "latitude": 56.8378,
        "longitude": 60.5974,
        "category_id": 6,
        "is_for_children": True,
        "age_rating_min": 6,
    },
    {
        "id": 140,
        "title": "Бег по набережной Рабочей молодёжи",
        "event_datetime": "2026-06-22T07:30:00+05:00",
        "location": "Набережная Рабочей молодёжи",
        "city": "Екатеринбург",
        "price": 0,
        "average_rating": 4.4,
        "cover_image_url": None,
        "latitude": 56.8268,
        "longitude": 60.5896,
        "category_id": 13,
        "is_for_children": True,
        "age_rating_min": 12,
    },
    {
        "id": 141,
        "title": "IT-митап: продукт и аналитика",
        "event_datetime": "2026-06-25T19:00:00+05:00",
        "location": "Коворкинг «Демидов»",
        "city": "Екатеринбург",
        "price": 0,
        "average_rating": 4.7,
        "cover_image_url": None,
        "latitude": 56.8486,
        "longitude": 60.5987,
        "category_id": 21,
        "is_for_children": False,
        "age_rating_min": 16,
    },
    {
        "id": 142,
        "title": "Дегустация уральских сыров",
        "event_datetime": "2026-06-29T17:00:00+05:00",
        "location": "Гастромаркет на площади 1905 года",
        "city": "Екатеринбург",
        "price": 1200,
        "average_rating": 4.5,
        "cover_image_url": None,
        "latitude": 56.8378,
        "longitude": 60.5974,
        "category_id": 17,
        "is_for_children": False,
        "age_rating_min": 18,
    },
]
